# Use Node.js base image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the frontend code
COPY . .

# Expose Vite port
EXPOSE 5173

# Run in development mode
CMD ["npm", "run", "dev"]
