# Generated by Django 5.2.6 on 2025-12-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('travel_request_submitted', 'Travel Request Submitted'), ('travel_request_approved', 'Travel Request Approved'), ('travel_request_rejected', 'Travel Request Rejected'), ('booking_confirmation', 'Booking Confirmation'), ('guest_house_confirmation', 'Guest House Booking Confirmation'), ('vehicle_duty_slip', 'Vehicle Duty Slip'), ('travel_reminder', 'Travel Reminder'), ('settlement_reminder', 'Settlement Reminder')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(help_text='Use {{variable}} for dynamic content')),
                ('body_text', models.TextField(blank=True, help_text='Optional plain-text fallback', null=True)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('bcc_emails', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('recipient_resolver', models.CharField(default='default_resolver', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('send_reminder', models.BooleanField(default=False)),
                ('reminder_intervals', models.JSONField(blank=True, default=list)),
                ('escalation_resolver', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.emailtemplatemaster')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.BigIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('next_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_index', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationrule')),
            ],
            options={
                'indexes': [models.Index(fields=['event_name'], name='notificatio_event_n_617ce5_idx'), models.Index(fields=['next_reminder_at'], name='notificatio_next_re_458cf9_idx')],
            },
        ),
    ]
