# Generated by Django 5.2.6 on 2025-12-11 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplatemaster',
            options={'ordering': ['template_key']},
        ),
        migrations.RemoveField(
            model_name='emailtemplatemaster',
            name='template_type',
        ),
        migrations.AddField(
            model_name='emailtemplatemaster',
            name='template_key',
            field=models.CharField(default=datetime.datetime(2025, 12, 11, 7, 39, 19, 234214, tzinfo=datetime.timezone.utc), help_text='Unique identifier used in NotificationRule (e.g., travel.submitted)', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplatemaster',
            name='template_name',
            field=models.CharField(default=datetime.datetime(2025, 12, 11, 7, 39, 52, 59158, tzinfo=datetime.timezone.utc), help_text='Readable name for admin panel (e.g., Travel Submitted Email)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplatemaster',
            name='body_html',
            field=models.TextField(help_text='\n        HTML body. Use template variables like {{ employee_name }}, {{ approver_name }},\n        {{ request_id }}, {{ purpose }} etc.\n        '),
        ),
        migrations.AlterField(
            model_name='emailtemplatemaster',
            name='body_text',
            field=models.TextField(blank=True, help_text='Optional plain text fallback. If empty, system auto-generates.', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplatemaster',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
