# Generated by Django 5.2.6 on 2025-10-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_citycategoryassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycategoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_category_assigment', to='master_data.citycategoriesmaster'),
        ),
    ]
