# Generated by Django 5.2.6 on 2025-10-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_designationmaster_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='grademaster',
            name='glcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.glcodemaster'),
        ),
    ]
