# Generated by Django 5.2.6 on 2025-11-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_alter_companyinformation_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelsuboptionmaster',
            options={'ordering': ['mode', 'name']},
        ),
        migrations.AddField(
            model_name='travelmodemaster',
            name='requires_city_category',
            field=models.BooleanField(default=False, help_text='Does this mode need city-based pricing? (e.g., Accommodation)'),
        ),
        migrations.AddField(
            model_name='travelmodemaster',
            name='requires_sub_option',
            field=models.BooleanField(default=True, help_text='Does this mode have sub-options? Set False for modes without variants'),
        ),
        migrations.CreateModel(
            name='GradeEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reimbursement amount (required for city-based modes)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='master_data.citycategoriesmaster')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='master_data.grademaster')),
                ('sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='master_data.travelsuboptionmaster')),
                ('travel_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_entitlements', to='master_data.travelmodemaster')),
            ],
            options={
                'indexes': [models.Index(fields=['grade', 'sub_option'], name='master_data_grade_i_f37478_idx'), models.Index(fields=['grade', 'travel_mode'], name='master_data_grade_i_6709a6_idx')],
                'unique_together': {('grade', 'sub_option', 'travel_mode', 'city_category')},
            },
        ),
    ]
