# Generated by Django 5.2.6 on 2025-11-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_alter_travelsuboptionmaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelsuboptionmaster',
            options={},
        ),
        migrations.RemoveField(
            model_name='travelmodemaster',
            name='requires_city_category',
        ),
        migrations.RemoveField(
            model_name='travelmodemaster',
            name='requires_sub_option',
        ),
        migrations.DeleteModel(
            name='GradeEntitlement',
        ),
    ]
