# Generated by Django 5.2.6 on 2025-11-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_alter_travelsuboptionmaster_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Rule', max_length=100)),
                ('use_company_code', models.BooleanField(default=False)),
                ('use_branch_code', models.BooleanField(default=False)),
                ('use_designation_code', models.BooleanField(default=False)),
                ('use_employee_type_code', models.BooleanField(default=False)),
                ('use_category_code', models.BooleanField(default=False)),
                ('use_date_code', models.BooleanField(default=False)),
                ('use_alpha_numeric', models.BooleanField(default=False)),
                ('use_running_number', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('order', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
