# Generated by Django 5.2.6 on 2025-11-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_employeecoderule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeCodeRule',
        ),
    ]
