# Generated by Django 5.2.6 on 2025-11-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_delete_employeecoderule'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmatrix',
            name='disposal_days_limit',
            field=models.IntegerField(blank=True, help_text='Max number of days for car disposal', null=True),
        ),
        migrations.AddField(
            model_name='approvalmatrix',
            name='distance_limit_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max distance allowed before CHRO approval is required', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='approvalmatrix',
            name='requires_chro_for_disposal',
            field=models.BooleanField(default=False, help_text='If car disposal exceeds days limit, require CHRO'),
        ),
        migrations.AddField(
            model_name='approvalmatrix',
            name='requires_chro_for_distance',
            field=models.BooleanField(default=False, help_text='If distance exceeds limit, require CHRO'),
        ),
    ]
