# Generated by Django 5.2.6 on 2025-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_approvalmatrix_disposal_days_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='flight_above_10k_ceo',
            field=models.BooleanField(default=False, help_text='Automatically require CEO approval for flights above ₹10,000'),
        ),
    ]
