# Generated by Django 5.2.6 on 2025-11-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_alter_approvalmatrix_flight_above_10k_ceo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplateMaster',
        ),
    ]
