# Generated by Django 5.2.6 on 2025-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_delete_emailtemplatemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glcodemaster',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
