# Generated by Django 5.2.6 on 2025-12-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_alter_glcodemaster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glcodemaster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
