# Generated by Django 5.2.6 on 2025-11-26 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0011_travelapplication_self_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_pending', 'Manager Pending'), ('finance_pending', 'Finance Pending'), ('chro_pending', 'CHRO Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('closed', 'Closed')], default='draft', max_length=50)),
                ('total_da', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_incidental', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount_payable', models.DecimalField(decimal_places=2, default=0, help_text='Positive = Payable to employee; Negative = Recoverable from employee', max_digits=10)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('late_submission_reason', models.TextField(blank=True)),
                ('exceptions', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to=settings.AUTH_USER_MODEL)),
                ('travel_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claim', to='travel.travelapplication')),
            ],
        ),
        migrations.CreateModel(
            name='DAIncidentalBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eligible_da', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('eligible_incidental', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('hours', models.DecimalField(decimal_places=2, default=0, help_text='Hours worked/travelled used for DA calculation', max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='da_breakdown', to='expenses.expenseclaim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='claims/docs/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='expenses.expenseclaim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('acted_on', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow', to='expenses.expenseclaim')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('taxi', 'Taxi'), ('auto', 'Auto / Local Travel'), ('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('meal', 'Meals'), ('fuel', 'Fuel'), ('toll', 'Toll'), ('parking', 'Parking'), ('misc', 'Miscellaneous')], max_length=50)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='claims/receipts/')),
                ('has_receipt', models.BooleanField(default=True)),
                ('is_self_certified', models.BooleanField(default=False)),
                ('self_certified_reason', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('city_category', models.CharField(blank=True, max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expenseclaim')),
            ],
        ),
    ]
