# Generated by Django 5.2.6 on 2025-11-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_terminal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('requires_receipt', models.BooleanField(default=True)),
                ('is_distance_based', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='expenses.claimstatusmaster'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_items', to='expenses.expensetypemaster'),
        ),
    ]
