# Generated by Django 5.2.6 on 2025-10-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country_name', 'state_name', 'city_name'],
                'unique_together': {('country_name', 'state_name', 'city_name')},
            },
        ),
    ]
