# Generated by Django 5.2.6 on 2025-10-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_citycategoryassignment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
