# Generated by Django 5.2.6 on 2025-10-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_companyinformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationmaster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='master_data.departmentmaster'),
        ),
    ]
