# Generated by Django 5.2.6 on 2025-10-27 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_base_location_user_company_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_submitted', models.BooleanField(default=True)),
                ('travel_approved', models.BooleanField(default=True)),
                ('travel_rejected', models.BooleanField(default=True)),
                ('booking_confirmed', models.BooleanField(default=True)),
                ('approval_required', models.BooleanField(default=True)),
                ('approval_reminder', models.BooleanField(default=True)),
                ('settlement_due', models.BooleanField(default=True)),
                ('settlement_overdue', models.BooleanField(default=True)),
                ('preferred_channels', models.JSONField(default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
