# Generated by Django 5.2.6 on 2025-11-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Non-binary'), ('N', 'Prefer not to say')], null=True, max_length=1),
        ),
    ]
