# Generated by Django 5.2.6 on 2025-11-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Non-binary'), ('N', 'Prefer not to say')], default='N', max_length=1),
        ),
    ]
