# Generated by Django 5.2.6 on 2025-11-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='dashboard_access',
            field=models.CharField(choices=[('employee', 'Employee Dashboard'), ('admin', 'Admin Dashboard'), ('travel_desk', 'Travel Desk Dashboard')], max_length=20),
        ),
    ]
