# Generated by Django 5.2.6 on 2025-11-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_role_dashboard_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='redirect_path',
            field=models.CharField(default='/employee/dashboard', help_text='Frontend redirect path after login for users with this role', max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='dashboard_access',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
