# Generated by Django 5.2.6 on 2025-11-18 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_role_redirect_path_alter_role_dashboard_access'),
        ('master_data', '0009_alter_travelsuboptionmaster_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='external_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_type', models.CharField(choices=[('booking_agent', 'Booking Agent'), ('hotel_vendor', 'Hotel Vendor'), ('transport_vendor', 'Transport Vendor'), ('airline_vendor', 'Airline Vendor'), ('consultant', 'Consultant'), ('other', 'Other')], default='other', max_length=50)),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('service_categories', models.JSONField(blank=True, default=list, help_text="List of service categories. Example: ['flight_booking', 'hotel_booking']")),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Profile',
                'verbose_name_plural': 'External Profiles',
                'db_table': 'external_profiles',
            },
        ),
        migrations.CreateModel(
            name='OrganizationalProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organizational_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizational Profile',
                'verbose_name_plural': 'Organizational Profiles',
                'db_table': 'organizational_profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='user_roles_user_id_50c4b6_idx',
            old_name='authenticat_user_id_cfb959_idx',
        ),
        migrations.RemoveField(
            model_name='role',
            name='dashboard_access',
        ),
        migrations.RemoveField(
            model_name='role',
            name='redirect_path',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organizational', 'Organizational User'), ('external', 'External User')], default='organizational', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(help_text='Role category (e.g., employee, admin, manager). No fixed choices.', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.locationmaster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.companyinformation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_department', to='master_data.departmentmaster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_designation', to='master_data.designationmaster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.employeetypemaster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.grademaster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permissions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
        migrations.AddField(
            model_name='organizationalprofile',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master_data.locationmaster'),
        ),
        migrations.AddField(
            model_name='organizationalprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master_data.companyinformation'),
        ),
        migrations.AddField(
            model_name='organizationalprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master_data.departmentmaster'),
        ),
        migrations.AddField(
            model_name='organizationalprofile',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master_data.designationmaster'),
        ),
        migrations.AddField(
            model_name='organizationalprofile',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master_data.employeetypemaster'),
        ),
        migrations.AddField(
            model_name='organizationalprofile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master_data.grademaster'),
        ),
        migrations.AddField(
            model_name='organizationalprofile',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
