# Generated by Django 5.2.6 on 2025-11-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_externalprofile_organizationalprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
