# Generated by Django 5.2.6 on 2025-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_notificationpreference'),
        ('master_data', '0014_delete_emailtemplatemaster'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationalprofile',
            index=models.Index(fields=['employee_id'], name='organizatio_employe_104b31_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalprofile',
            index=models.Index(fields=['company'], name='organizatio_company_9223b3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalprofile',
            index=models.Index(fields=['department'], name='organizatio_departm_ba2b08_idx'),
        ),
    ]
