# Generated by Django 5.2.6 on 2025-09-29 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('vendor_reference', models.CharField(blank=True, max_length=100)),
                ('booking_file', models.FileField(blank=True, null=True, upload_to=' booking_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.travelmodemaster')),
                ('sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.travelsuboptionmaster')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(help_text='Purpose of travel')),
                ('internal_order', models.CharField(help_text='IO reference number', max_length=50)),
                ('sanction_number', models.CharField(help_text='Sanction number for approval', max_length=50)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Advance amount requested', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_manager', 'Pending Manager Approval'), ('approved_manager', 'Approved by Manager'), ('rejected_manager', 'Rejected by Manager'), ('pending_chro', 'Pending CHRO Approval'), ('approved_chro', 'Approved by CHRO'), ('rejected_chro', 'Rejected by CHRO'), ('pending_ceo', 'Pending CEO Approval'), ('approved_ceo', 'Approved by CEO'), ('rejected_ceo', 'Rejected by CEO'), ('pending_travel_desk', 'Pending Travel Desk'), ('booking_in_progress', 'Booking in Progress'), ('booked', 'Bookings Confirmed'), ('completed', 'Travel Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('is_settled', models.BooleanField(default=False)),
                ('settlement_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_applications', to=settings.AUTH_USER_MODEL)),
                ('general_ledger', models.ForeignKey(help_text='GL code for expenses', on_delete=django.db.models.deletion.PROTECT, to='master_data.glcodemaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_to_review', to=settings.AUTH_USER_MODEL)),
                ('travel_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='travel.travelapplication')),
            ],
        ),
        migrations.CreateModel(
            name='TravelApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(choices=[('manager', 'Reporting Manager'), ('chro', 'CHRO'), ('ceo', 'CEO'), ('travel_desk', 'Travel Desk')], max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('can_view', models.BooleanField(default=True)),
                ('can_approve', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('triggered_by_rule', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('travel_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='travel.travelapplication')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('ticket', 'Travel Ticket'), ('hotel_voucher', 'Hotel Voucher'), ('duty_slip', 'Vehicle Duty Slip'), ('bill', 'Bill/Invoice'), ('receipt', 'Payment Receipt'), ('approval_document', 'Approval Document'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='travel_documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='travel.booking')),
                ('travel_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travel.travelapplication')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('trip_purpose', models.TextField(blank=True, help_text='Specific purpose for this trip segment')),
                ('guest_count', models.PositiveIntegerField(default=0, help_text='Number of guests accompanying')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='master_data.locationmaster')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='master_data.locationmaster')),
                ('travel_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_details', to='travel.travelapplication')),
            ],
            options={
                'ordering': ['departure_date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.tripdetails'),
        ),
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('guest_house', 'TSF Guest House'), ('arc_hotel', 'ARC Hotel'), ('non_arc_hotel', 'Non-ARC Hotel'), ('staying_with_friends', 'Staying with Friends/Relatives')], max_length=30)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('hotel_name', models.CharField(blank=True, max_length=200)),
                ('hotel_contact', models.CharField(blank=True, max_length=100)),
                ('hotel_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('guest_house_requested', 'Guest House Requested'), ('guest_house_confirmed', 'Guest House Confirmed'), ('guest_house_rejected', 'Guest House Rejected'), ('arc_hotel_requested', 'ARC Hotel Requested'), ('arc_hotel_confirmed', 'ARC Hotel Confirmed'), ('arc_hotel_rejected', 'ARC Hotel Rejected'), ('alternative_hotel_booked', 'Alternative Hotel Booked'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('room_type', models.CharField(blank=True, max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('rate_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('arc_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.archotelmaster')),
                ('guest_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.guesthousemaster')),
                ('trip_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_bookings', to='travel.tripdetails')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('pickup_drop', 'Airport/Station Pickup & Drop'), ('local_transport', 'Local Transportation'), ('inter_city', 'Inter-city Travel'), ('disposal', 'Car at Disposal'), ('own_car', 'Own Car')], max_length=20)),
                ('pickup_location', models.CharField(max_length=200)),
                ('drop_location', models.CharField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('estimated_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=8, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=15)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('own_car_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('spoc_notified', 'SPOC Notified'), ('vehicle_assigned', 'Vehicle Assigned'), ('duty_slip_generated', 'Duty Slip Generated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('duty_slip_number', models.CharField(blank=True, max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_spoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.locationspoc')),
                ('trip_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_bookings', to='travel.tripdetails')),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.vehicletypemaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='travelapplication',
            index=models.Index(fields=['employee', 'status'], name='travel_trav_employe_b46994_idx'),
        ),
        migrations.AddIndex(
            model_name='travelapplication',
            index=models.Index(fields=['status', 'current_approver'], name='travel_trav_status_9c519a_idx'),
        ),
        migrations.AddIndex(
            model_name='travelapplication',
            index=models.Index(fields=['created_at'], name='travel_trav_created_f63a79_idx'),
        ),
        migrations.AddIndex(
            model_name='travelapprovalflow',
            index=models.Index(fields=['travel_application', 'sequence'], name='travel_trav_travel__986962_idx'),
        ),
        migrations.AddIndex(
            model_name='travelapprovalflow',
            index=models.Index(fields=['approver', 'status'], name='travel_trav_approve_b4a76c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='travelapprovalflow',
            unique_together={('travel_application', 'approver', 'approval_level')},
        ),
        migrations.AddIndex(
            model_name='traveldocument',
            index=models.Index(fields=['travel_application', 'document_type'], name='travel_trav_travel__6bd4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='traveldocument',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='travel_trav_uploade_320d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='tripdetails',
            index=models.Index(fields=['travel_application', 'departure_date'], name='travel_trip_travel__3ac1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trip_details', 'booking_type'], name='travel_book_trip_de_429dac_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='travel_book_status_0ce8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationbooking',
            index=models.Index(fields=['trip_details', 'status'], name='travel_acco_trip_de_52a529_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationbooking',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='travel_acco_check_i_10527c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclebooking',
            index=models.Index(fields=['trip_details', 'status'], name='travel_vehi_trip_de_91df91_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclebooking',
            index=models.Index(fields=['assigned_spoc', 'status'], name='travel_vehi_assigne_c66a9d_idx'),
        ),
    ]
