# Generated by Django 5.2.6 on 2025-10-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_instruction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TravelAdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('train_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lodging_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conveyance_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_instruction', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_advance', to='travel.tripdetails')),
            ],
        ),
    ]
