# Generated by Django 5.2.6 on 2025-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booking_special_instruction_traveladvancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapprovalflow',
            name='parallel_group',
            field=models.CharField(blank=True, help_text='Group ID for parallel approvals', max_length=50, null=True),
        ),
    ]
