# Generated by Django 5.2.6 on 2025-10-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_alter_companyinformation_logo_and_more'),
        ('travel', '0006_alter_tripdetails_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='master_data.locationmaster'),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='master_data.locationmaster'),
        ),
    ]
