# Generated by Django 5.2.6 on 2025-10-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_tripdetails_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelapplication',
            name='sanction_number',
            field=models.CharField(blank=True, help_text='Sanction number for approval', max_length=50, null=True),
        ),
    ]
