# Generated by Django 5.2.6 on 2025-11-21 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_travelapplication_sanction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Exact end time of travel', null=True),
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated one-way distance in kilometers', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Exact start time of travel'),
            preserve_default=False,
        ),
    ]
