# Generated by Django 5.2.6 on 2025-11-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_tripdetails_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='self_approved',
            field=models.BooleanField(default=False),
        ),
    ]
