# Generated by Django 5.2.6 on 2025-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_travelapplication_self_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelapprovalflow',
            name='approval_level',
            field=models.CharField(choices=[('self_approval', 'Self Approval'), ('manager', 'Reporting Manager'), ('chro', 'CHRO'), ('ceo', 'CEO'), ('travel_desk', 'Travel Desk')], max_length=20),
        ),
    ]
