# Generated by Django 5.2.6 on 2025-12-05 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_travelapprovalflow_approval_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='travelapplication',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Advance amount requested', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
