# Generated by Django 5.2.6 on 2025-12-06 09:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_travelapprovalflow_approval_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='booking_completed_at',
            field=models.DateTimeField(blank=True, help_text='When all bookings were confirmed.', null=True),
        ),
        migrations.AddField(
            model_name='travelapplication',
            name='booking_forwarded_at',
            field=models.DateTimeField(blank=True, help_text='When the application was first forwarded to booking agent(s).', null=True),
        ),
        migrations.AddField(
            model_name='travelapplication',
            name='travel_desk_user',
            field=models.ForeignKey(blank=True, help_text='Primary travel desk owner handling this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_desk_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('submit', 'Submitted'), ('cancel', 'Cancelled'), ('assign_booking', 'Booking Assigned'), ('update_booking_status', 'Booking Status Updated'), ('forward_to_travel_desk', 'Forwarded to Travel Desk')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('in_progress', 'In Progress'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelapplication',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Advance amount requested', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_scope', models.CharField(choices=[('single_booking', 'Single Booking'), ('full_application', 'Full Application')], default='single_booking', help_text='Whether this assignment was created individually or via full application forwarding.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_received', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='travel.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='travel.booking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TravelApproval',
        ),
        migrations.AddIndex(
            model_name='bookingassignment',
            index=models.Index(fields=['assigned_to', 'assigned_at'], name='travel_book_assigne_136358_idx'),
        ),
    ]
