# Generated by Django 5.2.6 on 2025-12-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_booking_estimated_cost_and_more'),
        ('travel', '0014_booking_uploaded_at_booking_uploaded_by'),
    ]

    operations = [
    ]
