# Generated by Django 5.2.6 on 2025-12-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_merge_20251208_0821'),
        ('travel', '0015_merge_20251211_0618'),
    ]

    operations = [
    ]
